# theory

q.no.1)What is NumPy, and why is it widely used in Python?

 -> numphy is a fundamental Python library for numerical computing. It provides a powerful N-dimensional array object and a vast collection of high-level mathematical functions to operate on these arrays, making it the bedrock of the scientific Python ecosystem.

q.no.2)How does broadcasting work in NumPy?

 -> In NumPy, that allows for arithmetic operations between arrays of different shapes. It eliminates the need for explicit loops, making code more efficient, concise, and readable.

q.no.3) What is a Pandas DataFrame ?

 -> this is two-dimensional, size-mutable, tabular data structure with labeled axes (rows and columns). Think of it as a spreadsheet or a SQL table in a Python environment. It is the most commonly used and powerful data structure in the Pandas library

q.no.4) Explain the use of the groupby() method in Pandas?



 -> this is  used to split a DataFrame into groups based on some criterion. It is a powerful and flexible tool for performing a series of operations in a single, efficient step, often referred to as the "split-apply-combine" strategy

q.no.5) Why is Seaborn preferred for statistical visualizations?

 -> this is  provides a high-level, dataset-oriented API that is specifically designed for creating complex statistical plots with minimal code. While it's built on top of Matplotlib, its key advantages make it the go-to choice for data scientists and analysts.

q.no.6) What are the differences between NumPy arrays and Python lists?

-> numpy arry are differ from python lists -
 numphy arry - this is Faster for numerical operations. Operations are vectorized, meaning they are performed on the entire array at once using highly optimized C code.

 pythn lists - this is Slower for numerical operations. Operations must be performed on each element individually, typically with a for loop, which has significant overhead.  

q.no.7) What is a heatmap, and when should it be used?

 -> A heatmap is a graphical representation of data where values in a matrix are represented as colors. It's a powerful tool for visualizing large amounts of data at a glance, making it easy to identify patterns, trends, and correlations.

q.no.8) What does the term “vectorized operation” mean in NumPy?

 -> vectorized operation applying a mathematical or logical operation to an entire array at once, without the need for an explicit Python for loop. This process is significantly faster and more efficient than traditional loops because the operations are executed by optimized, pre-compiled C code under the hood

 ->  basically matplotilbare differ from  plitly -
  matplotlib- It's primarily designed for creating static, publication-quality plots. This makes it ideal for academic papers, reports, and presentations where a high degree of customization and control is necessary.
  plotly-Its primary output is an interactive HTML file or an embedded web visualization. This is perfect for dashboards, web applications, or data exploration in a Jupyter Notebook where users need to interact with the data.

q.no.10)What is the significance of hierarchical indexing in Pandas?

 ->Hierarchical indexing, also known as MultiIndex, is a powerful feature in the Pandas library that allows you to have multiple levels of indexing on a single axis. This lets you work with high-dimensional data in a two-dimensional format, effectively giving you a way to structure and organize complex datasets.

q.no.11) What is the role of Seaborn’s pairplot() function

 -> Seaborn's pairplot() function creates a grid of plots visualizing pairwise relationships in a dataset. It's a powerful tool for exploratory data analysis (EDA) that helps you quickly understand the structure of your data, including correlations between variables and the distribution of each variable.

q.no.12)What is the purpose of the describe() function in Pandas?

-> describe() function used for generating a summary of the descriptive statistics of a DataFrame or Series. Its purpose is to provide a quick and easy way to understand the central tendency, dispersion, and shape of your data's distribution.  

q.no.13) Why is handling missing data important in Pandas?

 -> handling missing is important for accuracy and reliability of your analysis. Missing values, represented as NaN (Not a Number) or None, can distort statistical calculations, lead to incorrect model predictions, and cause errors in your code.

q.no.14)  What are the benefits of using Plotly for data visualization?

 -> the  primary benefits  ability to go beyond static images and create engaging,  Dynamic Visualizations,Web-Friendly and Shareable,High-Level and Low-Level APIs,Advanced Chart Types and Aesthetics

q.no.15) How does NumPy handle multidimensional arrays?

 -> NumPy handles multidimensional arrays by storing all elements in a single, contiguous block of memory. This approach provides several performance benefits and is a fundamental design choice that distinguishes NumPy arrays from nested Python lists.

q.no.16) What is the role of Bokeh in data visualization?

 ->Bokeh's role in data visualization is to create interactive and web-friendly plots and dashboards. Unlike libraries like Matplotlib, which primarily generates static images, Bokeh is designed from the ground up to produce visualizations that can be easily embedded into web applications or Jupyter notebooks

q.no.17) Explain the difference between apply() and map() in Pandas

-> map() - is used for element-wise mapping or substitution. It takes a dictionary, a Series, or a function as an argument and applies it to each element of the Series, replacing the old values with the new ones.

  apply()-  It applies a function along an axis of a DataFrame or to each element of a Series. When used on a DataFrame, you can specify the axis (axis=0 for columns, axis=1 for rows), allowing the function to operate on an entire row or column at a time.

q.no.18) What are some advanced features of NumPy?

 -> NumPy's advanced features go beyond basic array creation and manipulation,broadcasting,univarsal function , advance idexing and slicling, offering powerful tools for high-performance computing, data analysis, and scientific research. These features are designed to handle complex numerical operations efficiently.




q.no.19) How does Pandas simplify time series analysis?


 -> Pandas simplifies time series analysis by providing a specialized data structure, the DatetimeIndex, and a rich set of functions that are optimized for handling and manipulating time-stamped data.or with the help of Resampling,Time-Based Slicing

q.no.20) A What is the role of a pivot table in Pandas?

 ->A pivot table in Pandas is a powerful tool for summarizing and aggregating data from a DataFrame. Its primary role is to reshape or reorganize data from a "long" format into a "wide," spreadsheet-like format, making it easier to analyze and gain insights.

q.no.21) A Why is NumPy’s array slicing faster than Python’s list slicing?

 -> NumPy's array slicing is faster than Python's list slicing is due to its fundamental design, Contiguous Memory Allocation ,Underlying C Implementation , No Type Checking like list,string,float


q.no.22) A What are some common use cases for Seaborn?

 ->Seaborn is a Python library for creating statistical graphics that is built on top of Matplotlib. It's often used for exploratory data analysis and to create visually appealing plots with less code

#  practical

q.no.1) How do you create a 2D NumPy array and calculate the sum of each row

In [ ]:
import numpy as np


matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Original 2D Array:")
print(matrix)
print("-" * 30)

row_sums = np.sum(matrix, axis=1)

print("Sum of each row:")
print(row_sums)

q.no.2) Write a Pandas script to find the mean of a specific column in a DataFrame

In [ ]:
import pandas as pd


data = {
    'product': ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry'],
    'price': [1.20, 0.50, 2.50, 3.10, 1.80],
    'quantity_sold': [150, 300, 75, 120, 200]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("-" * 30)

average_price = df['price'].mean()

print(f"The mean of the 'price' column is: {average_price:.2f}")

q.no.3) Create a scatter plot using Matplotlib

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
x = np.random.rand(50) * 100
y = x + np.random.randn(50) * 20

plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='blue', alpha=0.6, edgecolors='k')

plt.title('Sample Scatter Plot of Two Variables')
plt.xlabel('X-axis Label')
plt.ylabel('Y-axis Label')
plt.grid(True)

plt.show()

q.no.4)  How do you calculate the correlation matrix using Seaborn and visualize it with a heatmap

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    'A': np.random.rand(100) * 10,
    'B': np.random.rand(100) * 20,
    'C': np.random.rand(100) * 5 + 5,
    'D': np.random.rand(100) * 15 - 5
}
df = pd.DataFrame(data)

df['E'] = df['A'] * 2 + np.random.randn(100)

correlation_matrix = df.corr()

print("Correlation Matrix:")
print(correlation_matrix)
print("\n" + "="*40 + "\n")

plt.figure(figsize=(8, 6))
sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap='coolwarm',
    fmt=".2f",
    linewidths=.5
)

plt.title('Correlation Heatmap')
plt.show()

q.no.5) Generate a bar plot using Plotly

In [ ]:
import pandas as pd
import plotly.express as px


data = {
    'Category': ['A', 'B', 'C', 'D', 'E'],
    'Value': [25, 40, 30, 55, 45]
}
df = pd.DataFrame(data)


fig = px.bar(
    df,
    x='Category',
    y='Value',
    title='Bar Plot of Categories and Values',
    labels={'Category': 'Product Category', 'Value': 'Total Sales'}
)


fig.show()

q.no.6)  Create a DataFrame and add a new column based on an existing column

In [ ]:
import pandas as pd

data = {
    'product_id': [101, 102, 103, 104, 105],
    'price': [10.50, 25.00, 5.75, 50.25, 12.00]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("-" * 30)

df['discounted_price'] = df['price'] * 0.9

print("Updated DataFrame with new column:")
print(df)

q.no.7) Write a program to perform element-wise multiplication of two NumPy arrays

In [ ]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

print("Array 1:", array1)
print("Array 2:", array2)
print("-" * 30)


result_op = array1 * array2
print("Result using the * operator (element-wise multiplication):")
print(result_op)
print("-" * 30)
result_func = np.multiply(array1, array2)
print("Result using np.multiply() function:")
print(result_func)

print("\nAre the results identical?", np.array_equal(result_op, result_func))

q.no.8)  Create a line plot with multiple lines using MatplotlibA


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
y3 = np.sin(x) * np.cos(x)
plt.figure(figsize=(10, 6))
plt.plot(x, y1, label='sin(x)', color='blue', linestyle='-')
plt.plot(x, y2, label='cos(x)', color='red', linestyle='--')
plt.plot(x, y3, label='sin(x) * cos(x)', color='green', linestyle=':')

plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Multiple Lines on a Matplotlib Plot')
plt.legend()
plt.show()

q.no.9) A Generate a Pandas DataFrame and filter rows where a column value is greater than a


In [ ]:
import pandas as pd

data = {
    'product': ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry'],
    'price': [1.20, 0.50, 2.50, 3.10, 1.80],
    'stock': [150, 300, 75, 120, 200]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
print("-" * 30)

filtered_df = df[df['stock'] > 100]

print("Filtered DataFrame (stock > 100):")
print(filtered_df)

q.no.10) A import pandas as pd



In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = np.random.randn(1000)
df = pd.DataFrame({'value': data})

sns.histplot(data=df, x='value', kde=True, bins=30)

plt.title('Histogram of a Normal Distribution')
plt.xlabel('Value')
plt.ylabel('Frequency')

plt.show()


o.no.11) Perform matrix multiplication using NumPy


In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
C1 = A @ B
print("Result using the @ operator:")
print(C1)
print("-" * 20)

C2 = np.dot(A, B)
print("Result using np.dot():")
print(C2)
print("-" * 20)

C3 = np.matmul(A, B)
print("Result using np.matmul():")
print(C3)
print("\nAre all results equal?", np.array_equal(C1, C2) and np.array_equal(C2, C3))

Result using the @ operator:
[[ 58  64]
 [139 154]]
--------------------
Result using np.dot():
[[ 58  64]
 [139 154]]
--------------------
Result using np.matmul():
[[ 58  64]
 [139 154]]

Are all results equal? True



q.no.12) Use Pandas to load a CSV file and display its first 5 rowsA


In [ ]:
import pandas as pd
df = pd.read_csv('data.csv')
print(df.head())

q.no.13) A Create a 3D scatter plot using Plotly

In [ ]:
import plotly.express as px
import pandas as pd
import numpy as np

np.random.seed(42)
df = pd.DataFrame({
    'x': np.random.rand(50),
    'y': np.random.rand(50),
    'z': np.random.rand(50),
    'category': np.random.choice(['A', 'B', 'C'], 50)
})

fig = px.scatter_3d(
    df,
    x='x',
    y='y',
    z='z',
    color='category',
    title='3D Scatter Plot Example'
)

fig.show()
fig_direct = px.scatter_3d(
    x=np.random.rand(50),
    y=np.random.rand(50),
    z=np.random.rand(50),
    color=np.random.choice(['Group 1', 'Group 2'], 50),
    title='3D Scatter Plot from Arrays'
)

fig_direct.show()